# Generated by Django 4.0.2 on 2022-03-10 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='course info', max_length=255, unique=True, verbose_name='Name of the course')),
                ('introduction', models.TextField(help_text='course introduction', verbose_name='intro of the course')),
                ('price', models.DecimalField(decimal_places=2, help_text='course price', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated time')),
                ('teacher', models.ForeignKey(help_text='course instructor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher of course')),
            ],
            options={
                'verbose_name': 'course info',
                'verbose_name_plural': 'course info',
                'ordering': ('price',),
            },
        ),
    ]
